### ISSUE TITLE
Mac OS下使用没有行号

### ISSUE THREAD

**Issue by howie6879** [Theigrams/My-Typora-Themes#1]
环境：
OS: catalina 10.15.1
Typora Version: Version 0.9.9.35.2 (4715)

问题：
直接下载此项目，将相关文件放入主题，渲染后行间代码块没行号，如下图：

![image](https://user-images.githubusercontent.com/17047388/102688699-5e6e8a00-4233-11eb-8e1f-c5b7370c9ff6.png)

**Comment by Theigrams** [comment]
请查看一下是不是`偏好设置` 中没开启行号

<img width="812" alt="image" src="https://user-images.githubusercontent.com/26341831/102704048-ab914100-42b1-11eb-99c6-025c236e9dc4.png">

**Comment by howie6879** [comment]
是的，不好意思，之前没有用这个配置，以为是你css样式提供的
谢谢 问题已经解决
