### ISSUE TITLE
请问可以在README 文本中增加一些样式的案例吗？

### ISSUE THREAD

**Issue by Yong2Sheng** [Theigrams/My-Typora-Themes#11]
我在你的这个网站上看到了很多有趣的样式： https://typora-dyzj-theme.vercel.app/
比如说红色标签，下划线、着重号、波浪线。隐藏文本， 还有一些很有趣的特效。

我对 Markdown 用得不是很多，所以不懂如何用你的主题来实现这些特效，所以请问能否将这些效果写入这个主题的 README.md 文档中，这样我们可以用这个 README 文档作为一个参考。

如果方便的话，也能否请你在这个 issue 下稍微介绍一些怎么实现这些特效，谢谢！

**Comment by Theigrams** [comment]
> 我在你的这个网站上看到了很多有趣的样式： https://typora-dyzj-theme.vercel.app/ 比如说红色标签，下划线、着重号、波浪线。隐藏文本， 还有一些很有趣的特效。
> 
> 我对 Markdown 用得不是很多，所以不懂如何用你的主题来实现这些特效，所以请问能否将这些效果写入这个主题的 README.md 文档中，这样我们可以用这个 README 文档作为一个参考。
> 
> 如果方便的话，也能否请你在这个 issue 下稍微介绍一些怎么实现这些特效，谢谢！

这个网站很有意思，但不是我做的，它的GitHub地址在 https://github.com/muggledy/typora-dyzj-theme，你可以去那看看。
