### ISSUE TITLE
请问如何修改行间公式的字体大小？

### ISSUE THREAD

**Issue by y2609832** [Theigrams/My-Typora-Themes#13]
行间公式字体对我来说有些太大了，请问如何修改

**Comment by Theigrams** [comment]
https://github.com/Theigrams/My-Typora-Themes/blob/2136822aba45a234f4a6bf589695599161ee4e82/g2.css#L127

我在 g2.css 中添加了一些注释，可以看到行间数学公式为 `[mdtype="math_block"]`，这时你只需修改 font-size 即可

**Comment by y2609832** [comment]
感谢你的回复！已解决！
