### ISSUE TITLE
代码块行标溢出问题

### ISSUE THREAD

**Issue by JERRY-Z-J-R** [Theigrams/My-Typora-Themes#14]
当开启代码块显示行标时，如果代码超过99行，那么行标的数字就会与分割线重合！

**Comment by dlPtr** [comment]
1、打开 `g2.css` 搜索 `.cm-s-inner .CodeMirror-linenumber`
2、注释掉 `width: 2ch !important`

**Comment by YiHaoJia** [comment]
> 当开启代码块显示行标时，如果代码超过99行，那么行标的数字就会与分割线重合！

请问怎么开启代码块显示行标呀，我的没有行标，也没有分割线。谢谢。
