### ISSUE TITLE
小小的意见

### ISSUE THREAD

**Issue by CYZ0225** [Theigrams/My-Typora-Themes#18]
你好 请问下, 行间公式能不能不要弄成蓝色的 这样就跟黑色的文字很突兀诶

**Comment by Theigrams** [comment]
> 你好 请问下, 行间公式能不能不要弄成蓝色的 这样就跟黑色的文字很突兀诶

在CSS文件内搜索`inline-math`，然后把颜色改成黑色即可

**Comment by CYZ0225** [comment]
已收！
