### ISSUE TITLE
无序列表只能显示实心圆点

### ISSUE THREAD

**Issue by chen020506** [Theigrams/My-Typora-Themes#21]
你好，在使用g2主题的时候无序列表只能显示实心圆点，无法正常显示空心圆点和方形。下图为效果图：

![image](https://user-images.githubusercontent.com/75600645/193975391-fa0f9aaa-035e-4c03-b0c0-7796b0d1ff55.png)

**Comment by pernalin9** [comment]
作者设置成这样的，如果想要设置成显示空心圆点和方形，将zj.css文件的第372-374行注释掉就行

该行内容为：

```css
#write ul {
    list-style-type: disc;
}
```

之后就显示为

![图片](https://user-images.githubusercontent.com/114353794/229673347-b3d3e6c9-3deb-407e-a0aa-5ebff7353086.png)

**Comment by chen020506** [comment]
谢谢谢谢，已成功更改，再次感谢！
