### ISSUE TITLE
请问如何调整，保持导出时内联公式的颜色

### ISSUE THREAD

**Issue by fyulingi** [Theigrams/My-Typora-Themes#24]
如题，导出pdf时蓝色的行间公式很好看，请问怎么调整css使其在导出时保留，谢谢~

**Comment by Theigrams** [comment]
在 `设置` ->`导出`->`PDF`-> `插入额外内容` 中输入以下代码片段：

```html
<style>
    /* 修改inlineMath的颜色 */
    mjx-container[jax="SVG"] {
    color: blue; /* 将颜色设置为蓝色 */
    font-size: 100% !important; /* 设置为你想要的大小 */
    }
    /* 修改displayMath的颜色 */
    mjx-container[jax="SVG"][display="true"] {
    color: green; /* 将颜色设置为绿色 */
    font-size: 100% !important; /* 设置为你想要的大小 */
    }
</style>
```

该例子中输出的行间公式为绿色，如果你想换成蓝色，将 `color: green;` 改成 `color: blue;` 即可


<img width="832" alt="image" src="https://github.com/Theigrams/My-Typora-Themes/assets/26341831/ad495911-70a9-4ff6-8079-8fce1a6eebb1">

**Comment by fyulingi** [comment]
谢谢！十分有帮助！
