### ISSUE TITLE
斜体显示不正常

### ISSUE THREAD

**Issue by young1203** [Theigrams/My-Typora-Themes#3]
*字体倾斜*   
功能不能实现，zj.css
#write em {
    padding: 0 2px 0 2px;
    font-style: normal;
    color: #ff3502;
    /* color: #595959;
    background: #F6EEFF; */
}

字体样式修改为：font-style: italic;

**Comment by Theigrams** [comment]
因为中文斜体比较难看，所以就特意把斜体换成红色显示了，算是这个主题的一个特性吧
