### ISSUE TITLE
可以调整背景色吗

### ISSUE THREAD

**Issue by che88she** [Theigrams/My-Typora-Themes#5]
白色有点亮眼，长期看有些刺眼，可以调成改成护眼色吗

**Comment by Theigrams** [comment]
![image](https://user-images.githubusercontent.com/26341831/126807150-f6d2f65e-7dbd-474e-8a2b-2d4b75f410c3.png)

找到这个 `windows.css` ，然后修改 `background-color` 成自己喜欢的颜色即可
