### ISSUE TITLE
导出为 PDF 后，有序列表或无序列表中的加粗效果不存在

### ISSUE THREAD

**Issue by WenvyG** [Theigrams/My-Typora-Themes#6]
对面北科的来给老哥点个 Star

这个主题条理清晰，分级明确，比起 Typora 内置的几个主题，它确实让我复习整理的时候方便了不少。

另外，在我用的过程中，帮老哥捉住了一只虫子：

在 Typora 中将文字格式设置为`有序列表`或`无序列表`，然后再将其内文字格式设置为`加粗`

- 在 Typora 中，`加粗`效果正常
- 在导出为 PDF 后，`加粗`效果不存在
- Typora 内置的 GitHub 主题则在导出为 PDF 后，`加粗`效果正常

水平有限，确实没找到这部分的配置在`.css`的什么地方

<img width="1699" alt="iShot2021-06-29 13 24 10" src="https://user-images.githubusercontent.com/66265944/123745732-457e1a00-d8e3-11eb-84b4-a4a0ee644c6f.png">

**Comment by Theigrams** [comment]
typora 是用 pandoc 来将 markdown 转化成 PDF 的，我看 [Pandoc - Pandoc User’s Guide](https://pandoc.org/MANUAL.html) 上的解释是先将 md 转化为 abstract syntax tree (AST)，再对 AST 运行一个 pandoc filters 进行修改，最后再从 AST 转化为其他格式。

而我只会一点入门级的 CSS，对 AST 和 pandoc 不太懂，所以对于这一块也无能为力。

如果有大佬能修复这个 bug，也希望能告诉我一下，谢谢。

**Comment by WenvyG** [comment]
感谢老哥的回复，不过我看了一遍 Typora 的文档，它在导出格式为 `PDF` 和`HTML`的时候是不会经过 Pandoc 的。

<img width="1180" alt="iShot2021-07-03 00 00 21" src="https://user-images.githubusercontent.com/66265944/124301068-e09c1b80-db91-11eb-9cf1-0c24de4302dc.png">

等之后有时间了，我再研究研究这个问题，如果解决了会给你反馈的👌👌👌

**Comment by lambda-001** [comment]
我在Zj.css文件中的@media print {}里的最后添加了以下代码解决了
`ol li strong,
    ol li b {
        font-weight: bold!important;
        color: #db4d52!important; 
    }
    
    #write ul li strong { 
	  font-weight: bold !important;
	  color: #db4d52 !important;
	}`

**Comment by lambda-001** [comment]
我在Zj.css文件中的https://github.com/media print {}里的最后添加了以下代码解决了
`ol li strong,
 ol li b {
      font-weight: bold!important;
      color: #db4d52!important; 
  }
  #write ul li strong { 
  font-weight: bold !important;
  color: #db4d52 !important;
 }`

**Comment by lambda-001** [comment]
在Zj.css文件中的media print里增加以下代码似乎解决了
```
ol li strong,
  ol li b {
      font-weight: bold!important;
      color: #db4d52!important; 
  }
  
  #write ul li strong { 
  font-weight: bold !important;
  color: #db4d52 !important;
}
```
