### ISSUE TITLE
下载哪个文件？

### ISSUE THREAD

**Issue by ECNUJason** [Theigrams/My-Typora-Themes#8]

**Comment by CarlBye** [comment]
zj.css和g2.css是主题，zj文件夹是字体，放在Theme Folder下面

**Comment by C-starm** [comment]
@ECNUJason 点击打开主题文件夹，把git clone 下来的东西仍进去，实在搞不定就百度
![2021-09-10 11-32-47 的屏幕截图](https://user-images.githubusercontent.com/17534292/132795381-6bc0f4f8-0341-48a3-93f1-17fd91bd012c.png)
