### ISSUE TITLE
代码块行数超过100行会出现行号越线的BUG，以及导出PDF时如果出现分页会出现红色边框渲染不齐的BUG

### ISSUE THREAD

**Issue by genskyff** [Theigrams/My-Typora-Themes#9]
## 如图
![image](https://user-images.githubusercontent.com/43875771/131856808-1c78b19e-eecc-4a24-a95d-111d5428f408.png)

![image](https://user-images.githubusercontent.com/43875771/131856895-da53ebb5-faa4-405d-ac95-176287df1422.png)

**Comment by Theigrams** [comment]
第二个问题我也遇到过，但我也不知道怎么解决，毕竟这不是 CSS 的问题，这是 typora 的 BUG。

至于第一个问题的话，我觉得文档中还是不要放太长的代码，过于喧宾夺主，放上核心代码就够了。
如果要使用的话，不妨把代码文件的路径地址放进去，这样一点链接就能打开。

**Comment by peng-yq** [comment]
第一个问题，修改css文件.cm-s-inner .CodeMirror-linenumber {
    width: 2ch !important;
    color: rgba(128, 128, 255, 0.8);
}
将width调大一些就行，我是改成3ch解决了
